FROM oven/bun:1-alpine AS frontend

WORKDIR /app/internal/site

COPY internal/site/package.json internal/site/bun.lock ./
RUN bun install --no-save

COPY internal/site/ ./
RUN bun run build

FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

# Download Go modules
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy source files
COPY . ./

# Copy the Vite output from the frontend stage
COPY --from=frontend /app/internal/site/dist ./internal/site/dist

RUN apk add --no-cache \
    unzip \
    ca-certificates

RUN update-ca-certificates

# Build
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /beszel ./internal/cmd/hub

# ? -------------------------
FROM scratch

COPY --from=builder /beszel /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Ensure data persistence across container recreations
VOLUME ["/beszel_data"]

EXPOSE 8090

ENTRYPOINT [ "/beszel" ]
CMD ["serve", "--http=0.0.0.0:8090"]